// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJN9i6WDlo6y9SVEHwBxE7G0Z4s7eB3ZY',
    appId: '1:494598481745:ios:d7d1035603f25c838c9570',
    messagingSenderId: '494598481745',
    projectId: 'foodx-atheer-2026',
    storageBucket: 'foodx-atheer-2026.firebasestorage.app',
    iosBundleId: 'com.example.foodxCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJN9i6WDlo6y9SVEHwBxE7G0Z4s7eB3ZY',
    appId: '1:494598481745:ios:d7d1035603f25c838c9570',
    messagingSenderId: '494598481745',
    projectId: 'foodx-atheer-2026',
    storageBucket: 'foodx-atheer-2026.firebasestorage.app',
    iosBundleId: 'com.example.foodxCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARxCJUbQeS8oEFf0pu91POGtsowygR3pE',
    appId: '1:494598481745:web:1dda20e6528afeb18c9570',
    messagingSenderId: '494598481745',
    projectId: 'foodx-atheer-2026',
    authDomain: 'foodx-atheer-2026.firebaseapp.com',
    storageBucket: 'foodx-atheer-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxCJUbQeS8oEFf0pu91POGtsowygR3pE',
    appId: '1:494598481745:web:1dda20e6528afeb18c9570',
    messagingSenderId: '494598481745',
    projectId: 'foodx-atheer-2026',
    authDomain: 'foodx-atheer-2026.firebaseapp.com',
    storageBucket: 'foodx-atheer-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvHEVPbkQ2zKHG_wfvpB-yAB8IkqAS7k',
    appId: '1:494598481745:android:0bdc6ae1e00390728c9570',
    messagingSenderId: '494598481745',
    projectId: 'foodx-atheer-2026',
    storageBucket: 'foodx-atheer-2026.firebasestorage.app',
  );
}
